import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { HeroHeader } from "@/components/layout/HeroHeader";
import Footer from "@/components/ui/footer";

export const metadata: Metadata = {
  title: "Işık Nakliyat | İstanbul Nakliyat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <HeroHeader />

          {children}
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
